### ISSUE TITLE
Toreless - draft-5 section 7.2: Internet vs Network with connectivity

### ISSUE THREAD

**Issue by mcr** [anima-wg/brski-cloud#85]
```
821	7.2.  Security Updates for the Pledge

823	   Unlike many other uses of BRSKI, in the Cloud Registrar case it is
824	   assumed that the Pledge has connected to a network on which there is

I don't think the Internet is Voldemort. Aka: feel free to globally replace
"the Internet". If it really could be another network than the Internet, thats
fine to keep explicitly, but for something like firmware updates specifically,
it clearly seems to be just the Internet.

```

**Comment by mcr** [comment]
@toerless I did not write The Internet for three reasons.

1. the pledge probably does not have a public IP address, and many people think that's what "The Internet" means.
2. there are networks in which NAT44 is also not available, but thanks to things like https://en.wikipedia.org/wiki/Web_Proxy_Auto-Discovery_Protocol, they can STILL do HTTP requests.  (I know of three gc.ca departments where this is still true). These are not quite, but almost, air-gapped networks.
3. I'm open to another term for such limited domains, but I'd really like to emphasize that we do not need connectivity to the entire Internet.

**Comment by toerless** [comment]
Well, the sentence in question is followed by:

764        There is another advantage to being online: the pledge may be able to
                                      ^^^^^^^^^^^^^^^^
765        contact the manufacturer before onboarding in order to apply the
766        latest firmware updates.

This makes it really hard to no imply that what the section writes about is being
"on the Internet / connected to the Internet"...

In any case, your explanations would be more useful if they where in the text
to make it clearer, what type of "online" is meant. Especially if its not
(only) the Internet.

Cheers
    Toerless
